#!/usr/bin/env python3
"""
Turns the design system's SVG assets into a single PHP file of theme-aware
markup.

The motifs ship twice, once per theme, but the two copies are geometrically
identical: diffing them shows only three hex values change. Two files per motif
means the page has to swap an image when somebody presses the theme switch,
which either flashes or lags. Swapping those three literals for custom
properties makes one file serve both themes and follow the switch in the same
frame as everything else.

Usage: python3 tools/build-assets.py <design/assets> <out.php>
"""

import pathlib
import re
import sys

# The three literals the light copy changes, and what they mean.
THEMED = {
    '#4fb8a5': 'var(--c-brand-graphic)',
    '#e8a33a': 'var(--c-accent)',
    '#eef1f4': 'var(--c-text-primary)',
}


def tokenise(svg):
    for literal, token in THEMED.items():
        svg = re.sub(literal, token, svg, flags=re.I)
    # The xmlns is only needed for a standalone file; inline it is noise.
    svg = svg.replace(' xmlns="http://www.w3.org/2000/svg"', '')
    return svg.strip()


def php_array(name, items, comment):
    out = ['\t/* %s */' % comment, "\t'%s' => array(" % name]
    for key, svg in sorted(items.items()):
        out.append("\t\t'%s' => '%s'," % (key, svg.replace('\\', '\\\\').replace("'", "\\'")))
    out.append('\t),')
    return '\n'.join(out)


def main(src, dest):
    src = pathlib.Path(src)

    icons = {f.stem: tokenise(f.read_text()) for f in sorted((src / 'icons').glob('*.svg'))}
    motifs = {f.stem: tokenise(f.read_text()) for f in sorted((src / 'thumbnails/dark').glob('*.svg'))}
    logos = {f.stem: tokenise(f.read_text()) for f in sorted((src / 'logo').glob('*.svg'))}

    body = '''<?php
/**
 * The design system's artwork, as inline markup.
 *
 * GENERATED by tools/build-assets.py. Inline rather than linked, because a
 * category grid is ten icons and a card row is six motifs, and thirty extra
 * requests to draw a homepage is thirty requests too many. It also lets the
 * artwork answer to the theme: the three colours that differ between the light
 * and dark copies of a motif are custom properties here, so one drawing serves
 * both and follows the switch in the same frame as the rest of the page.
 *
 * Anything absent falls back to its category icon rather than to nothing,
 * because the tile is on every card, row and page title, and ten icons cover
 * only nine of a hundred and five calculators.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
%s
%s
%s
);
''' % (
        php_array('icons', icons, 'Category, tool and interface icons, 24px, currentColor'),
        php_array('motifs', motifs, 'Thumbnail motifs, 384 wide, anchored right'),
        php_array('logos', logos, 'The logo mark for each surface'),
    )

    pathlib.Path(dest).write_text(body)
    print('%s written: %d icons, %d motifs, %d logos' % (dest, len(icons), len(motifs), len(logos)))


if __name__ == '__main__':
    main(sys.argv[1], sys.argv[2])
