#!/usr/bin/env python3
"""
Generates assets/css/tokens.css from the design system's tokens.json.

Written as a generator rather than typed out, because the system carries 33
colours in two themes plus five other scales, and a hand-copied value that is
one digit wrong is invisible until somebody measures contrast on the wrong
page. Running this again after a token change is the whole point.

Two corrections are applied on the way through, and they are declared here
rather than edited into the output, so regenerating cannot silently undo them:

  accent (light)      #e8a33a -> #b77715
      Amber was the one token identical in both themes. Against light surfaces
      the shipped value measures 1.88 to 2.16:1, which fails even the 3:1 bar
      for a graphic that carries meaning, and amber carries meaning everywhere
      it appears: the notice icon, the interest arc, the answer dot. The
      replacement keeps the hue and clears 3:1 on every light surface while
      leaving near-black text on an amber fill at 4.84:1.

  text-subtle (light) #656d76 -> #616971
      The spec measures this on surface-sunken, where it passes at 4.57:1, but
      surface-hover is that same element with a cursor on it and drops to
      4.29:1. Text that passes at rest and fails on hover is worse than text
      that fails outright, because nobody tests for it.

Usage: python3 tools/build-tokens.py <tokens.json> <out.css>
"""

import json
import sys

CORRECTIONS = {
    'accent': {'light': '#b77715'},
    'text-subtle': {'light': '#616971'},
}

HEADER = """/*
 * Design tokens for calculatorr.org.
 *
 * GENERATED by tools/build-tokens.py from the design system's tokens.json.
 * Edit the source and regenerate rather than editing this file, or the next
 * regeneration will quietly throw the edit away.
 *
 * Dark is the base palette. A visitor whose device asks for light gets light,
 * and whichever the visitor picks with the switch wins over both, which is why
 * the explicit attribute is declared last and carries the higher specificity.
 *
 * Two attribute names are honoured. data-theme is what the design system
 * specifies; data-calcr-theme is what the site shipped with, and it is kept so
 * that a preference already stored in somebody's browser still applies.
 */
"""


def declarations(colors, mode, indent='\t'):
    out = []
    for name, spec in colors.items():
        value = CORRECTIONS.get(name, {}).get(mode, spec[mode])
        out.append('%s--c-%s: %s;' % (indent, name, value))
    return '\n'.join(out)


def unit(value):
    """Numbers in the scales are pixels unless they are plainly a ratio."""
    if isinstance(value, (int, float)):
        return '%gpx' % value if abs(value) >= 1 else '%g' % value
    return str(value)


def scale(data, prefix, indent='\t'):
    """Flattens a scale, including the nested ones, and drops any entry whose
    value is prose rather than a value: the tile radius is documented as a
    ratio with a worked table, which is guidance for a human and not a
    declaration a browser can use."""
    out = []

    for name, value in data.items():
        if isinstance(value, dict):
            for sub, inner in value.items():
                if isinstance(inner, (int, float)):
                    out.append('%s--%s-%s-%s: %s;' % (indent, prefix, name, sub, unit(inner)))
                elif isinstance(inner, str) and not inner.startswith('http') and ';' not in inner and len(inner) < 60:
                    out.append('%s--%s-%s-%s: %s;' % (indent, prefix, name, sub, inner))
        elif isinstance(value, (int, float)):
            out.append('%s--%s-%s: %s;' % (indent, prefix, name, unit(value)))
        elif isinstance(value, str) and not value.startswith('http') and ';' not in value \
                and 'x tile size' not in value and not value.startswith('no '):
            out.append('%s--%s-%s: %s;' % (indent, prefix, name, value))

    return '\n'.join(out)


COMPAT = """
\t/* ------------------------------------------------------------ compat -- */

\t/*
\t * The names the site already uses, redefined in terms of the design system
\t * rather than replaced. Around twelve hundred lines of stylesheet, the
\t * homepage markup and the Design tab all reference these, and a rename in
\t * one pass is how a redesign turns into a week of hunting for the one rule
\t * that still points at nothing. Custom properties resolve at the point of
\t * use, so a component still reading --calcr-ink follows the theme correctly
\t * through this layer and can be migrated on its own schedule.
\t */
\t--calcr-paper: var(--c-bg-page);
\t--calcr-surface: var(--c-surface-card);
\t--calcr-ink: var(--c-text-primary);
\t--calcr-ink-soft: var(--c-text-secondary);
\t--calcr-muted: var(--c-text-muted);
\t--calcr-subtle: var(--c-text-subtle);
\t--calcr-line: var(--c-border-default);
\t--calcr-line-strong: var(--c-border-strong);
\t--calcr-sunken: var(--c-surface-sunken);
\t--calcr-accent: var(--c-brand);
\t--calcr-accent-ink: var(--c-on-brand);
\t--calcr-accent-soft: var(--c-brand-tint);
\t--calcr-accent-line: var(--c-brand-tint-border);
\t--calcr-warn: var(--c-accent);
\t--calcr-warn-soft: var(--c-notice-bg);
\t--calcr-warn-line: var(--c-notice-border);
\t--calcr-warn-ink: var(--c-notice-text);
\t--calcr-neutral-mark: var(--c-text-subtle);
\t--calcr-footer-bg: var(--c-bg-footer);
\t--calcr-footer-ink: var(--c-text-secondary);
\t--calcr-footer-strong: var(--c-text-primary);
\t--calcr-footer-quiet: var(--c-text-subtle);
\t--calcr-footer-line: var(--c-border-divider);
\t--calcr-font-display: var(--f-display-family);
\t--calcr-font-body: var(--f-body-family);
\t--calcr-radius-sm: var(--radius-logo-tile);
\t--calcr-radius: var(--radius-button);
\t--calcr-radius-lg: var(--radius-search-form);
\t--calcr-radius-xl: var(--radius-category-card-desktop);
\t--calcr-touch: var(--size-touch-target-min);
\t--calcr-container: 1200px;

\t/*
\t * The page gutter, and the only one on the site.
\t *
\t * The artboards are drawn on a 1440 canvas with 120px either side, which
\t * is 8.34vw, so this lands on the design's figure at the width it was
\t * designed at and scales from there. Every page type uses it, because a
\t * homepage that runs to the edge and a calculator page that stops short
\t * of it read as two different sites however well each one is drawn.
\t *
\t * It stops growing at 120px so the content does not drift apart on a very
\t * wide screen, and the phone figure is capped separately below, since a
\t * gutter that tracks the viewport this steeply eats a 390px screen.
\t */
\t--calcr-gutter: clamp(24px, 8.34vw, 120px);
\t--calcr-header-height: var(--size-header-height-desktop);
\t--calcr-gap-xs: var(--space-stack-xs);
\t--calcr-gap-sm: var(--space-stack-s);
\t--calcr-gap: var(--space-stack-m);
\t--calcr-gap-lg: var(--space-stack-l);
"""

# The footer is dark in light mode no longer: the design system flips it with
# everything else, so the wordmark has to stop being unconditionally inverted.
THEMED_COMPAT = {
    'dark': '\t--calcr-shadow: rgba( 0, 0, 0, 0.45 );\n\t--calcr-logo-filter: invert( 1 ) hue-rotate( 180deg );',
    'light': '\t\t--calcr-shadow: rgba( 20, 24, 29, 0.13 );\n\t\t--calcr-logo-filter: none;',
}


def build(tokens):
    colors = tokens['color']
    light_changes = {k: v for k, v in colors.items() if v['light'] != v['dark']}
    # A correction can introduce a light value where the source had none.
    for name in CORRECTIONS:
        light_changes.setdefault(name, colors[name])

    parts = [HEADER]

    parts.append(':root,\n:root[data-theme="dark"],\n:root[data-calcr-theme="dark"] {\n\tcolor-scheme: dark;\n')
    parts.append(declarations(colors, 'dark'))
    parts.append('\n')
    parts.append(scale(tokens['font'], 'f'))
    parts.append('\n')
    parts.append(scale(tokens['space'], 'space'))
    parts.append('\n')
    parts.append(scale(tokens['radius'], 'radius'))
    parts.append('\n')
    parts.append(scale(tokens['size'], 'size'))
    parts.append('\n')
    parts.append(scale(tokens['motion'], 'motion'))
    parts.append(COMPAT)
    parts.append(THEMED_COMPAT['dark'])
    parts.append('}\n')

    light_block = declarations(light_changes, 'light', '\t\t')

    parts.append('\n/* The device asks for light and the visitor has not overridden it. */')
    parts.append('@media ( prefers-color-scheme: light ) {\n\t:root:not([data-theme="dark"]):not([data-calcr-theme="dark"]) {\n\t\tcolor-scheme: light;\n')
    parts.append(light_block)
    parts.append(THEMED_COMPAT['light'])
    parts.append('\t}\n}\n')

    parts.append('\n/* The visitor chose light, which beats the device either way. */')
    parts.append(':root[data-theme="light"],\n:root[data-calcr-theme="light"] {\n\t\tcolor-scheme: light;\n')
    parts.append(light_block)
    parts.append(THEMED_COMPAT['light'])
    parts.append('}\n')

    return '\n'.join(parts)


if __name__ == '__main__':
    with open(sys.argv[1]) as fh:
        tokens = json.load(fh)

    css = build(tokens)

    with open(sys.argv[2], 'w') as fh:
        fh.write(css)

    print('%s written, %d bytes' % (sys.argv[2], len(css)))
