<?php
/**
 * Generated file. Do not edit by hand.
 *
 * Each calculator's server-rendered default result, computed from its own
 * formula by tools/build-defaults.js so the HTML a crawler indexes can never
 * disagree with what the script produces in the browser.
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

return array(
	'401k-calculator' => array(
		'label' => 'Balance after 30 years',
		'value' => '$1,095,898',
		'note'  => 'Contributing at or above the match limit, which is the first thing to get right before anything else in a retirement plan.',
		'rows'  => array(
			array( 'label' => 'Your contributions', 'value' => '$239,089' ),
			array( 'label' => 'Employer match', 'value' => '$107,045' ),
			array( 'label' => 'Investment growth', 'value' => '$749,764' ),
			array( 'label' => 'First year contribution', 'value' => '$4,500' ),
			array( 'label' => 'First year match', 'value' => '$2,250' ),
		),
	),
	'age-calculator' => array(
		'label' => 'Age',
		'value' => '36 years',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Exactly', 'value' => '36y 8m 17d' ),
			array( 'label' => 'Total days', 'value' => '13,409' ),
			array( 'label' => 'Total weeks', 'value' => '1,915' ),
			array( 'label' => 'Total months', 'value' => '440' ),
		),
	),
	'amortization-calculator' => array(
		'label' => 'Monthly payment',
		'value' => '$1,896.20',
		'note'  => 'The payment never changes but its split does. Early on almost all of it is interest, which is why the balance seems to barely move for the first few years.',
		'rows'  => array(
			array( 'label' => 'Total interest', 'value' => '$382,633' ),
			array( 'label' => 'Total paid', 'value' => '$682,633' ),
			array( 'label' => 'First payment interest', 'value' => '$1,625.00' ),
			array( 'label' => 'First payment principal', 'value' => '$271.20' ),
			array( 'label' => 'Year one interest', 'value' => '$19,401' ),
			array( 'label' => 'Balance after a year', 'value' => '$296,647' ),
		),
	),
	'ap-score-calculator' => array(
		'label' => 'Estimated AP score',
		'value' => '4',
		'note'  => 'An indication rather than a prediction. The College Board sets the cut points separately for every subject every year and does not publish them, so the real boundaries move. Treat a borderline result as genuinely uncertain.',
		'rows'  => array(
			array( 'label' => 'Composite', 'value' => '69.7%' ),
			array( 'label' => 'Multiple choice', 'value' => '40 of 55' ),
			array( 'label' => 'Free response', 'value' => '18 of 27' ),
			array( 'label' => 'Typically earns credit', 'value' => 'yes at most colleges' ),
		),
	),
	'area-calculator' => array(
		'label' => 'Rectangle area',
		'value' => '120 sq units',
		'note'  => 'Area is unitless here: whatever unit you measure in, the answer is in that unit squared. Mixing feet and inches in the same calculation is the usual source of a wrong answer.',
		'rows'  => array(
			array( 'label' => 'If units are feet', 'value' => '120 sq ft' ),
			array( 'label' => 'If units are metres', 'value' => '120 m2' ),
			array( 'label' => 'Square inches to square feet', 'value' => '0.8333' ),
		),
	),
	'average-calculator' => array(
		'label' => 'Mean average',
		'value' => '18',
		'note'  => 'The mean is pulled by outliers and the median is not, so when the two disagree sharply the median usually describes the data better.',
		'rows'  => array(
			array( 'label' => 'Median', 'value' => '15.5' ),
			array( 'label' => 'Mode', 'value' => 'none repeats' ),
			array( 'label' => 'Count', 'value' => '6' ),
			array( 'label' => 'Sum', 'value' => '108' ),
			array( 'label' => 'Range', 'value' => '38' ),
		),
	),
	'bac-calculator' => array(
		'label' => 'Estimated BAC',
		'value' => '0.040%',
		'note'  => 'A rough population estimate from the Widmark formula, not a measurement. Food, medication, body composition, liver function and how fast you drank all move the real figure, often by a lot. Never use this to decide whether to drive. If you have been drinking, do not drive.',
		'rows'  => array(
			array( 'label' => 'Status', 'value' => 'Under 0.05' ),
			array( 'label' => 'Peak before metabolism', 'value' => '0.070%' ),
			array( 'label' => 'Pure alcohol consumed', 'value' => '1.8 fl oz' ),
			array( 'label' => 'Hours until zero', 'value' => '2.7' ),
		),
	),
	'bmi-calculator' => array(
		'label' => 'Body mass index',
		'value' => '22.9',
		'note'  => 'BMI cannot tell muscle from fat, so it overstates risk for athletes and understates it for anyone sedentary with a light frame.',
		'rows'  => array(
			array( 'label' => 'Category', 'value' => 'Healthy weight' ),
			array( 'label' => 'Healthy range', 'value' => '18.5 to 24.9' ),
		),
	),
	'board-foot-calculator' => array(
		'label' => 'Board feet',
		'value' => '8 bd ft',
		'note'  => 'Board feet are measured on nominal rough thickness, so a board sold as one inch is counted as one inch even after it is planed down to three quarters.',
		'rows'  => array(
			array( 'label' => 'Per piece', 'value' => '8 bd ft' ),
			array( 'label' => 'Pieces', 'value' => '1' ),
			array( 'label' => 'Total cost', 'value' => '$0.00' ),
		),
	),
	'boat-loan-calculator' => array(
		'label' => 'Monthly payment',
		'value' => '$449.60',
		'note'  => 'Boat loans run longer than car loans, commonly fifteen to twenty years, which keeps the payment low and the total interest high. Budget separately for mooring, insurance, winterising and maintenance, which together often exceed the loan payment.',
		'rows'  => array(
			array( 'label' => 'Amount financed', 'value' => '$48,500' ),
			array( 'label' => 'Total interest', 'value' => '$32,428' ),
			array( 'label' => 'Total of payments', 'value' => '$80,928' ),
			array( 'label' => 'Number of payments', 'value' => '180' ),
			array( 'label' => 'Cost per dollar borrowed', 'value' => '$1.67' ),
		),
	),
	'body-fat-calculator' => array(
		'label' => 'Body fat',
		'value' => '17.2%',
		'note'  => 'The US Navy tape method, which is typically within about three or four percentage points of a DEXA scan. It is far better than BMI at telling body composition, and far worse than a scan. Measure at the same time of day for comparable readings.',
		'rows'  => array(
			array( 'label' => 'Category', 'value' => 'Fitness' ),
			array( 'label' => 'Fat mass', 'value' => '31 lb' ),
			array( 'label' => 'Lean mass', 'value' => '149 lb' ),
		),
	),
	'body-surface-area-calculator' => array(
		'label' => 'Body surface area',
		'value' => '1.926 m2',
		'note'  => 'Mosteller is shown as the headline because it is the formula most commonly used for drug dosing, being both simple and about as accurate as the longer ones. Where a dose depends on this, the prescriber’s own formula is the one that counts.',
		'rows'  => array(
			array( 'label' => 'Mosteller', 'value' => '1.9257 m2' ),
			array( 'label' => 'Du Bois', 'value' => '1.9267 m2' ),
			array( 'label' => 'Haycock', 'value' => '1.9295 m2' ),
			array( 'label' => 'Square feet', 'value' => '20.73' ),
		),
	),
	'bra-size-calculator' => array(
		'label' => 'Estimated size',
		'value' => '82I',
		'note'  => 'Sizing is not standardised between brands, so treat this as a starting point and expect to try a size either side. If the cup fits but the band rides up, the sister sizes above are the ones to try.',
		'rows'  => array(
			array( 'label' => 'Band', 'value' => '82' ),
			array( 'label' => 'Cup', 'value' => 'I (9 in difference)' ),
			array( 'label' => 'Sister size down', 'value' => '80J' ),
			array( 'label' => 'Sister size up', 'value' => '84H' ),
		),
	),
	'business-days-calculator' => array(
		'label' => 'Business days',
		'value' => '22',
		'note'  => 'Both the start and end dates are counted, which is the convention for contractual notice periods. Public holidays are entered by hand because they differ by country and by state.',
		'rows'  => array(
			array( 'label' => 'Calendar days', 'value' => '30' ),
			array( 'label' => 'Weekend days', 'value' => '8' ),
			array( 'label' => 'Weekdays before holidays', 'value' => '22' ),
			array( 'label' => 'Holidays deducted', 'value' => '0' ),
			array( 'label' => 'Working weeks', 'value' => '4.4' ),
		),
	),
	'cd-calculator' => array(
		'label' => 'Value at maturity',
		'value' => '$10,459.40',
		'note'  => 'The rate is locked for the term, which is the point of a CD and also its cost: withdrawing early usually forfeits several months of interest, and you cannot take advantage if rates rise.',
		'rows'  => array(
			array( 'label' => 'Interest earned', 'value' => '$459.40' ),
			array( 'label' => 'Principal', 'value' => '$10,000.00' ),
			array( 'label' => 'Effective annual yield', 'value' => '4.594%' ),
			array( 'label' => 'Term', 'value' => '12 months' ),
			array( 'label' => 'Interest per month, averaged', 'value' => '$38.28' ),
		),
	),
	'celsius-to-fahrenheit-calculator' => array(
		'label' => '20°C converted',
		'value' => '68°F',
		'note'  => 'The two scales meet at minus forty, which is the same temperature in Celsius and Fahrenheit and the only point where they agree.',
		'rows'  => array(
			array( 'label' => 'Celsius', 'value' => '20°C' ),
			array( 'label' => 'Fahrenheit', 'value' => '68°F' ),
			array( 'label' => 'Kelvin', 'value' => '293.15 K' ),
			array( 'label' => 'Reference', 'value' => 'liquid water range' ),
		),
	),
	'chronological-age-calculator' => array(
		'label' => 'Age',
		'value' => '36 years',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Exactly', 'value' => '36y 8m 17d' ),
			array( 'label' => 'Total days', 'value' => '13,409' ),
			array( 'label' => 'Total weeks', 'value' => '1,915' ),
			array( 'label' => 'Total months', 'value' => '440' ),
		),
	),
	'circumference-calculator' => array(
		'label' => 'Circumference',
		'value' => '31.415927',
		'note'  => 'Every circle has the same ratio of circumference to diameter, and that ratio is pi. It is why one measurement of a circle gives you all the others.',
		'rows'  => array(
			array( 'label' => 'Radius', 'value' => '5' ),
			array( 'label' => 'Diameter', 'value' => '10' ),
			array( 'label' => 'Area', 'value' => '78.539816' ),
			array( 'label' => 'Quarter turn along the edge', 'value' => '7.853982' ),
		),
	),
	'compound-interest-calculator' => array(
		'label' => 'Balance after 20 years',
		'value' => '$170,619',
		'note'  => 'Assumes the rate holds for the whole period and ignores tax, inflation and fees, all of which reduce what the balance is actually worth.',
		'rows'  => array(
			array( 'label' => 'You put in', 'value' => '$70,000' ),
			array( 'label' => 'Interest earned', 'value' => '$100,619' ),
			array( 'label' => 'Starting amount', 'value' => '$10,000' ),
			array( 'label' => 'Monthly contribution', 'value' => '$250' ),
		),
	),
	'concrete-calculator' => array(
		'label' => 'Concrete to order',
		'value' => '1.36 cubic yards',
		'note'  => 'Above roughly one cubic yard, ready-mix delivered by truck is usually cheaper and far less work than bags.',
		'rows'  => array(
			array( 'label' => 'Volume', 'value' => '36.7 cu ft' ),
			array( 'label' => 'Metric', 'value' => '1.04 m3' ),
			array( 'label' => '80 lb bags', 'value' => '62' ),
			array( 'label' => '60 lb bags', 'value' => '82' ),
			array( 'label' => '40 lb bags', 'value' => '123' ),
		),
	),
	'cpm-calculator' => array(
		'label' => 'CPM',
		'value' => '$5.00',
		'note'  => 'CPM is cost per thousand impressions, from the Latin mille. It measures reach rather than response, so a low CPM on an audience that never converts is more expensive than a high one that does.',
		'rows'  => array(
			array( 'label' => 'Cost', 'value' => '$2,500.00' ),
			array( 'label' => 'Impressions', 'value' => '500,000' ),
			array( 'label' => 'CPM', 'value' => '$5.00' ),
			array( 'label' => 'Clicks at 0.5% CTR', 'value' => '2,500' ),
			array( 'label' => 'Effective cost per click', 'value' => '$1.00' ),
		),
	),
	'cubic-feet-calculator' => array(
		'label' => 'Volume',
		'value' => '27 cu ft',
		'note'  => 'Shipping and storage are quoted in cubic feet, and a standard moving box is about 1.5. Freight is normally billed on whichever is greater, the volume or the weight.',
		'rows'  => array(
			array( 'label' => 'Cubic yards', 'value' => '1' ),
			array( 'label' => 'Cubic metres', 'value' => '0.7646' ),
			array( 'label' => 'Cubic inches', 'value' => '46,656' ),
			array( 'label' => 'US gallons', 'value' => '201.97' ),
			array( 'label' => 'Litres', 'value' => '764.6' ),
		),
	),
	'cubic-yard-calculator' => array(
		'label' => 'Volume',
		'value' => '1.85 cubic yards',
		'note'  => 'One cubic yard is 27 cubic feet, which is the conversion most order mistakes come down to.',
		'rows'  => array(
			array( 'label' => 'Cubic feet', 'value' => '50' ),
			array( 'label' => 'Cubic metres', 'value' => '1.42' ),
			array( 'label' => 'Cubic inches', 'value' => '86,400' ),
		),
	),
	'cumulative-gpa-calculator' => array(
		'label' => 'Cumulative GPA',
		'value' => '3.48',
		'note'  => 'The more credits already banked, the less any single term moves the average. That is why a weak first year is recoverable and a weak final year usually is not.',
		'rows'  => array(
			array( 'label' => 'Change this term', 'value' => '+0.08' ),
			array( 'label' => 'Total credits', 'value' => '75' ),
			array( 'label' => 'Total quality points', 'value' => '261' ),
			array( 'label' => 'To reach 3.5 you would need', 'value' => '3.6 next term over 15 credits' ),
		),
	),
	'cylinder-volume-calculator' => array(
		'label' => 'Cylinder volume',
		'value' => '282.7433 cubic units',
		'note'  => 'Doubling the radius quadruples the volume while doubling the height only doubles it, which is why wide tanks hold so much more than tall ones of the same material.',
		'rows'  => array(
			array( 'label' => 'Radius used', 'value' => '3' ),
			array( 'label' => 'If units are inches, in gallons', 'value' => '1.224' ),
			array( 'label' => 'If units are feet, in gallons', 'value' => '2,115.07' ),
			array( 'label' => 'Curved surface area', 'value' => '188.496' ),
			array( 'label' => 'Total surface area', 'value' => '245.044' ),
		),
	),
	'date-calculator' => array(
		'label' => 'Resulting date',
		'value' => 'Sat, Feb 28, 2026',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Day of the week', 'value' => 'Saturday' ),
			array( 'label' => 'Days from the start', 'value' => '28' ),
			array( 'label' => 'ISO format', 'value' => '2026-02-28' ),
			array( 'label' => 'Day of the year', 'value' => '59' ),
		),
	),
	'decimal-to-fraction-calculator' => array(
		'label' => '0.375 as a fraction',
		'value' => '3/8',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Improper form', 'value' => '3/8' ),
			array( 'label' => 'Back to decimal', 'value' => '0.375' ),
			array( 'label' => 'As a percentage', 'value' => '37.5%' ),
		),
	),
	'deck-calculator' => array(
		'label' => 'Decking to buy',
		'value' => '458 linear ft',
		'note'  => 'Joist count assumes a simple rectangular frame and excludes rim joists, blocking and stairs, which are worth adding before you order.',
		'rows'  => array(
			array( 'label' => 'Deck area', 'value' => '192 sq ft' ),
			array( 'label' => 'Board rows', 'value' => '26' ),
			array( 'label' => 'Joists at 16in centres', 'value' => '13' ),
			array( 'label' => 'If buying 16ft boards', 'value' => '29 boards' ),
		),
	),
	'derivative-calculator' => array(
		'label' => 'Derivative',
		'value' => 'f\'(x) = 6x + 5',
		'note'  => 'Differentiated term by term with the power rule. Understood: powers such as 3x^2, plain terms such as 5x or 7, sin(x), cos(x), e^x, ln(x) and sqrt(x), added or subtracted. Products, quotients and nested functions are not supported yet.',
		'rows'  => array(
			array( 'label' => 'Original', 'value' => 'f(x) = 3x^2 + 5x - 7' ),
			array( 'label' => 'Slope at x = 2', 'value' => '17' ),
			array( 'label' => 'f(x) at that point', 'value' => '15' ),
		),
	),
	'discount-calculator' => array(
		'label' => 'You pay',
		'value' => '$90.00',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Original price', 'value' => '$120.00' ),
			array( 'label' => 'You save', 'value' => '$30.00' ),
			array( 'label' => 'Effective discount', 'value' => '25%' ),
		),
	),
	'distance-calculator' => array(
		'label' => 'Distance between the points',
		'value' => '5',
		'note'  => 'The distance formula is the Pythagorean theorem with the horizontal and vertical changes as the two legs.',
		'rows'  => array(
			array( 'label' => 'Horizontal change', 'value' => '3' ),
			array( 'label' => 'Vertical change', 'value' => '4' ),
			array( 'label' => 'Midpoint', 'value' => '(1.5, 2)' ),
			array( 'label' => 'Slope', 'value' => '1.3333' ),
		),
	),
	'dividend-calculator' => array(
		'label' => 'Annual dividend income',
		'value' => '$1,200.00',
		'note'  => 'Reinvesting means each payment buys more shares, which then pay their own dividends. That compounding is where most of the long-run return in dividend investing comes from.',
		'rows'  => array(
			array( 'label' => 'Dividend yield', 'value' => '4.8%' ),
			array( 'label' => 'Per payment', 'value' => '$300.00' ),
			array( 'label' => 'Invested', 'value' => '$25,000.00' ),
			array( 'label' => 'Income over 20 years', 'value' => '$69,043' ),
			array( 'label' => 'Shares after 20 years', 'value' => '1,277.01' ),
			array( 'label' => 'Portfolio value then', 'value' => '$169,415' ),
		),
	),
	'dog-age-calculator' => array(
		'label' => 'In human years',
		'value' => '39 years',
		'note'  => 'The size table is shown as the headline because breed size affects ageing more than anything else: small dogs commonly reach sixteen while giant breeds rarely pass ten. The times-seven rule is included only to show how far off it is early on.',
		'rows'  => array(
			array( 'label' => 'By the size table', 'value' => '39 years' ),
			array( 'label' => 'By the epigenetic formula', 'value' => '56.8 years' ),
			array( 'label' => 'Old times-seven rule', 'value' => '35 years' ),
			array( 'label' => 'Dog age entered', 'value' => '5 years' ),
		),
	),
	'ebay-fee-calculator' => array(
		'label' => 'Profit on the sale',
		'value' => '$23.02',
		'note'  => 'The fee rate is entered rather than fixed, because eBay charges differently by category and by store subscription and changes the rates periodically. Note that the final value fee applies to the shipping the buyer pays as well as to the item price, which is the part sellers most often miss.',
		'rows'  => array(
			array( 'label' => 'Buyer pays', 'value' => '$58.00' ),
			array( 'label' => 'eBay fees', 'value' => '$7.99' ),
			array( 'label' => 'Your item cost', 'value' => '$20.00' ),
			array( 'label' => 'Your shipping cost', 'value' => '$7.00' ),
			array( 'label' => 'Profit margin', 'value' => '39.68%' ),
			array( 'label' => 'Break-even sale price', 'value' => '$23.47' ),
		),
	),
	'factor-calculator' => array(
		'label' => 'Factors of 360',
		'value' => '24 factors',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'All factors', 'value' => '1, 2, 3, 4, 5, 6, 8, 9, 10, 12, 15, 18, 20, 24, 30, 36, 40, 45, 60, 72, 90, 120, 180, 360' ),
			array( 'label' => 'Prime factorisation', 'value' => '2^3 × 3^2 × 5' ),
			array( 'label' => 'Prime number', 'value' => 'no' ),
			array( 'label' => 'Sum of factors', 'value' => '1170' ),
		),
	),
	'feet-to-meters-calculator' => array(
		'label' => '6 ft in m',
		'value' => '1.8288 m',
		'note'  => 'A foot is exactly 0.3048 metres by definition, so three feet is a little under a metre and the two are close enough that people often confuse them.',
		'rows'  => array(
			array( 'label' => 'Centimetres', 'value' => '182.88' ),
			array( 'label' => 'Metres', 'value' => '1.8288' ),
			array( 'label' => 'Inches', 'value' => '72' ),
			array( 'label' => 'Feet', 'value' => '6' ),
		),
	),
	'fraction-calculator' => array(
		'label' => '1/2 + 1/3',
		'value' => '5/6',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'As a decimal', 'value' => '0.833333' ),
			array( 'label' => 'As a percentage', 'value' => '83.3333%' ),
			array( 'label' => 'Improper form', 'value' => '5/6' ),
		),
	),
	'future-value-calculator' => array(
		'label' => 'Future value',
		'value' => '$264,122',
		'note'  => 'The figure in today’s money is the one worth planning against, because a balance that looks large in thirty years buys considerably less than the same number does now.',
		'rows'  => array(
			array( 'label' => 'Total paid in', 'value' => '$130,000' ),
			array( 'label' => 'Interest earned', 'value' => '$134,122' ),
			array( 'label' => 'Periods', 'value' => '240' ),
			array( 'label' => 'Worth in today’s money', 'value' => '$146,238' ),
		),
	),
	'gcf-calculator' => array(
		'label' => 'Greatest common factor',
		'value' => '12',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Lowest common multiple', 'value' => '720' ),
			array( 'label' => 'Numbers', 'value' => '48, 180' ),
			array( 'label' => 'Shared factors', 'value' => '1, 2, 3, 4, 6, 12' ),
			array( 'label' => 'Coprime', 'value' => 'no' ),
		),
	),
	'gpa-calculator' => array(
		'label' => 'Grade point average',
		'value' => '4',
		'note'  => 'Uses the unweighted four point scale, so honours and AP courses are not given extra weight here.',
		'rows'  => array(
			array( 'label' => 'Courses counted', 'value' => '3' ),
			array( 'label' => 'Total credits', 'value' => '9' ),
			array( 'label' => 'Quality points', 'value' => '36' ),
		),
	),
	'gravel-calculator' => array(
		'label' => 'Gravel to order',
		'value' => '2.04 cubic yards',
		'note'  => 'Weight is an average and varies with moisture and grade, so confirm the supplier’s own figure before ordering by the ton rather than by volume.',
		'rows'  => array(
			array( 'label' => 'Volume', 'value' => '55 cu ft' ),
			array( 'label' => 'Metric', 'value' => '1.56 m3' ),
			array( 'label' => 'Approx. weight', 'value' => '2.85 US tons' ),
		),
	),
	'gst-calculator' => array(
		'label' => 'Total including GST',
		'value' => '$110.00',
		'note'  => 'Removing GST means dividing by one plus the rate, not subtracting the percentage. Subtracting gives a number that is always too low, and the gap grows with the size of the bill.',
		'rows'  => array(
			array( 'label' => 'Excluding GST', 'value' => '$100.00' ),
			array( 'label' => 'GST amount', 'value' => '$10.00' ),
			array( 'label' => 'Including GST', 'value' => '$110.00' ),
			array( 'label' => 'Rate applied', 'value' => '10%' ),
		),
	),
	'heloc-calculator' => array(
		'label' => 'Available credit line',
		'value' => '$132,500',
		'note'  => 'The draw period is usually interest-only, and the jump when repayment starts catches people out badly. The payment shock row is the size of that jump. A HELOC is also secured on your home, so the downside of not paying is losing it.',
		'rows'  => array(
			array( 'label' => 'Home equity', 'value' => '$200,000' ),
			array( 'label' => 'Current loan-to-value', 'value' => '55.6%' ),
			array( 'label' => 'Interest-only payment on $50,000', 'value' => '$354.17' ),
			array( 'label' => 'Repayment phase, 20 years', 'value' => '$433.91' ),
			array( 'label' => 'Payment shock', 'value' => '$79.74' ),
		),
	),
	'hours-calculator' => array(
		'label' => 'Hours worked',
		'value' => '8h 0m',
		'note'  => 'Payroll systems usually work in decimal hours rather than hours and minutes, so 8h 30m is entered as 8.5.',
		'rows'  => array(
			array( 'label' => 'Decimal hours', 'value' => '8' ),
			array( 'label' => 'Break deducted', 'value' => '30 min' ),
			array( 'label' => 'Gross time on site', 'value' => '8h 30m' ),
			array( 'label' => 'Pay at $20.00/hr', 'value' => '$160.00' ),
		),
	),
	'inches-to-feet-calculator' => array(
		'label' => '78 in in ft',
		'value' => '6.5 ft',
		'note'  => 'Twelve inches to the foot, so the decimal part of the answer is not inches: 6.5 feet is six feet and six inches, not six feet five.',
		'rows'  => array(
			array( 'label' => 'Feet and inches', 'value' => '6 ft 6 in' ),
			array( 'label' => 'Centimetres', 'value' => '198.12' ),
			array( 'label' => 'Metres', 'value' => '1.9812' ),
			array( 'label' => 'Inches', 'value' => '78' ),
			array( 'label' => 'Feet', 'value' => '6.5' ),
		),
	),
	'integral-calculator' => array(
		'label' => 'Indefinite integral',
		'value' => '∫ f(x) dx = 0.333333x^3 + C',
		'note'  => 'Integrated term by term with the reverse power rule. The constant of integration is written as C because an indefinite integral describes a family of curves rather than one. Understood: powers such as 3x^2, plain terms such as 5x or 7, sin(x), cos(x), e^x, ln(x) and sqrt(x), added or subtracted. Products, quotients and nested functions are not supported yet.',
		'rows'  => array(
			array( 'label' => 'Original', 'value' => 'f(x) = x^2' ),
			array( 'label' => 'Definite from 0 to 3', 'value' => '9' ),
		),
	),
	'lcm-calculator' => array(
		'label' => 'Lowest common multiple',
		'value' => '12',
		'note'  => 'For two numbers the LCM times the GCF always equals the two numbers multiplied together, which is a quick way to check the answer.',
		'rows'  => array(
			array( 'label' => 'Greatest common factor', 'value' => '2' ),
			array( 'label' => 'Numbers', 'value' => '4, 6' ),
			array( 'label' => 'Prime factors of the LCM', 'value' => '2 × 2 × 3' ),
		),
	),
	'long-division-calculator' => array(
		'label' => '847 ÷ 23',
		'value' => '36 remainder 19',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Quotient', 'value' => '36' ),
			array( 'label' => 'Remainder', 'value' => '19' ),
			array( 'label' => 'As a decimal', 'value' => '36.82608696' ),
			array( 'label' => 'As a mixed number', 'value' => '36 19/23' ),
		),
	),
	'love-calculator' => array(
		'label' => 'Compatibility',
		'value' => '89%',
		'note'  => 'For fun only. This is a hash of two names and nothing more, so it has no predictive value whatsoever. It will give the same answer every time for the same pair, which is the only honest claim it can make.',
		'rows'  => array(
			array( 'label' => 'Verdict', 'value' => 'Written in the stars' ),
			array( 'label' => 'Names', 'value' => 'Alex and Sam' ),
		),
	),
	'macro-calculator' => array(
		'label' => 'Balanced macros',
		'value' => '150P / 200C / 67F',
		'note'  => 'Protein is the macro worth hitting accurately, because it protects muscle in a deficit and is the most filling of the three. The carbohydrate and fat split is far more a matter of preference and adherence than most advice admits.',
		'rows'  => array(
			array( 'label' => 'Protein', 'value' => '150 g  (30%)' ),
			array( 'label' => 'Carbohydrate', 'value' => '200 g  (40%)' ),
			array( 'label' => 'Fat', 'value' => '67 g  (30%)' ),
			array( 'label' => 'Total calories', 'value' => '2,000 kcal' ),
		),
	),
	'margin-calculator' => array(
		'label' => 'Price for a 40% margin',
		'value' => '$66.67',
		'note'  => 'Margin is profit as a share of the selling price, which is the figure that matters for a profit and loss account. Markup is the same profit measured against cost.',
		'rows'  => array(
			array( 'label' => 'Cost', 'value' => '$40.00' ),
			array( 'label' => 'Gross profit', 'value' => '$26.67' ),
			array( 'label' => 'Equivalent markup', 'value' => '66.67%' ),
			array( 'label' => 'Cost as a share of price', 'value' => '60%' ),
		),
	),
	'markup-calculator' => array(
		'label' => 'Selling price',
		'value' => '$60.00',
		'note'  => 'Markup and margin are not the same number and confusing them is how businesses quietly underprice. A 50% markup is only a 33% margin, because markup is measured against cost and margin against the selling price.',
		'rows'  => array(
			array( 'label' => 'Cost', 'value' => '$40.00' ),
			array( 'label' => 'Profit per unit', 'value' => '$20.00' ),
			array( 'label' => 'Markup', 'value' => '50%' ),
			array( 'label' => 'Resulting margin', 'value' => '33.33%' ),
		),
	),
	'military-pay-calculator' => array(
		'label' => 'Monthly gross',
		'value' => '$5,760.00',
		'note'  => 'Base pay, BAH and BAS are entered rather than looked up, because the tables change every January and BAH depends on duty ZIP code and dependant status. Take the current figures from your LES or the DFAS pay tables. Regular Military Compensation is the honest number to compare against a civilian salary, because it reflects that the allowances arrive untaxed.',
		'rows'  => array(
			array( 'label' => 'Taxable pay', 'value' => '$3,500.00' ),
			array( 'label' => 'Tax-free allowances', 'value' => '$2,260.00' ),
			array( 'label' => 'Annual gross', 'value' => '$69,120' ),
			array( 'label' => 'Allowances grossed up', 'value' => '$2,897.44' ),
			array( 'label' => 'Regular Military Compensation', 'value' => '$6,397.44' ),
			array( 'label' => 'RMC annualised', 'value' => '$76,769' ),
		),
	),
	'military-time-converter' => array(
		'label' => '2:30 PM in military time',
		'value' => '1430',
		'note'  => 'Midnight is 0000 and noon is 1200. There is no 2400 in normal use, since the day rolls over to 0000.',
		'rows'  => array(
			array( 'label' => 'With a colon', 'value' => '14:30' ),
			array( 'label' => 'Minutes past midnight', 'value' => '870' ),
		),
	),
	'mm-to-inches-calculator' => array(
		'label' => '100 mm in in',
		'value' => '3.93701 in',
		'note'  => 'Divide millimetres by 25.4 to get inches. For a quick mental check, 25 mm is almost exactly an inch.',
		'rows'  => array(
			array( 'label' => 'Centimetres', 'value' => '10' ),
			array( 'label' => 'Metres', 'value' => '0.1' ),
			array( 'label' => 'Inches', 'value' => '3.93701' ),
			array( 'label' => 'Feet', 'value' => '0.32808' ),
		),
	),
	'molarity-calculator' => array(
		'label' => 'Molarity',
		'value' => '1 M',
		'note'  => 'Molarity is moles of solute per litre of solution, not per litre of solvent. Dissolving something changes the volume, so make the solution up to the mark rather than adding solute to a litre of water.',
		'rows'  => array(
			array( 'label' => 'Moles of solute', 'value' => '1 mol' ),
			array( 'label' => 'Molar mass', 'value' => '58.44 g/mol' ),
			array( 'label' => 'Millimolar', 'value' => '1,000 mM' ),
		),
	),
	'mortgage-payment-calculator' => array(
		'label' => 'Monthly payment',
		'value' => '$2,759',
		'note'  => 'Excludes mortgage insurance, HOA dues and closing costs, which vary too much by lender and property to estimate honestly.',
		'rows'  => array(
			array( 'label' => 'Principal & interest', 'value' => '$2,275' ),
			array( 'label' => 'Property tax', 'value' => '$350' ),
			array( 'label' => 'Home insurance', 'value' => '$133' ),
			array( 'label' => 'Loan amount', 'value' => '$360,000' ),
			array( 'label' => 'Total interest paid', 'value' => '$459,160' ),
			array( 'label' => 'Total cost of loan', 'value' => '$909,160' ),
		),
	),
	'mortgage-payoff-calculator' => array(
		'label' => 'Paid off in',
		'value' => '19 yr 6 mo',
		'note'  => 'Every extra dollar goes straight at the principal, which removes its interest from every remaining month. That is why overpaying early saves so much more than overpaying later.',
		'rows'  => array(
			array( 'label' => 'Interest saved', 'value' => '$64,928' ),
			array( 'label' => 'Time saved', 'value' => '5 yr 6 mo' ),
			array( 'label' => 'New monthly payment', 'value' => '$1,888.02' ),
			array( 'label' => 'Original payment', 'value' => '$1,688.02' ),
			array( 'label' => 'Interest without overpaying', 'value' => '$256,405' ),
			array( 'label' => 'Interest when overpaying', 'value' => '$191,477' ),
		),
	),
	'mulch-calculator' => array(
		'label' => 'Mulch to order',
		'value' => '2.04 cubic yards',
		'note'  => 'Weight is an average and varies with moisture and grade, so confirm the supplier’s own figure before ordering by the ton rather than by volume.',
		'rows'  => array(
			array( 'label' => 'Volume', 'value' => '55 cu ft' ),
			array( 'label' => 'Metric', 'value' => '1.56 m3' ),
			array( 'label' => 'Approx. weight', 'value' => '1.02 US tons' ),
			array( 'label' => '2 cu ft bags', 'value' => '28' ),
		),
	),
	'one-rep-max-calculator' => array(
		'label' => 'Estimated one rep max',
		'value' => '114.6 kg',
		'note'  => 'Averaged from the two most widely used formulas. They agree closely under about six reps and diverge above it.',
		'rows'  => array(
			array( 'label' => 'Epley formula', 'value' => '116.7 kg' ),
			array( 'label' => 'Brzycki formula', 'value' => '112.5 kg' ),
			array( 'label' => '95% for 2 reps', 'value' => '108.9 kg' ),
			array( 'label' => '90% for 4 reps', 'value' => '103.1 kg' ),
			array( 'label' => '80% for 8 reps', 'value' => '91.7 kg' ),
			array( 'label' => '70% for 12 reps', 'value' => '80.2 kg' ),
		),
	),
	'overtime-calculator' => array(
		'label' => 'Gross pay',
		'value' => '$1,100.00',
		'note'  => 'Under the federal FLSA, overtime is time and a half above forty hours in a week for non-exempt employees. Several states are more generous, so check your own before assuming forty is the threshold.',
		'rows'  => array(
			array( 'label' => 'Regular, 40 h', 'value' => '$800.00' ),
			array( 'label' => 'Overtime at 1.5x', 'value' => '$300.00' ),
			array( 'label' => 'Double time', 'value' => '$0.00' ),
			array( 'label' => 'Effective hourly rate', 'value' => '$22.00' ),
			array( 'label' => 'Total hours', 'value' => '50' ),
		),
	),
	'ovulation-calculator' => array(
		'label' => 'Estimated ovulation',
		'value' => 'Tue, Sep 15, 2026',
		'note'  => 'An estimate from cycle arithmetic, not an observation. Real ovulation shifts by several days between cycles even in regular ones, so treat the window as wider than the dates suggest and use tracking rather than a calendar if timing matters.',
		'rows'  => array(
			array( 'label' => 'Fertile window opens', 'value' => 'Thu, Sep 10, 2026' ),
			array( 'label' => 'Most fertile', 'value' => 'Mon, Sep 14, 2026 to Tue, Sep 15, 2026' ),
			array( 'label' => 'Fertile window closes', 'value' => 'Wed, Sep 16, 2026' ),
			array( 'label' => 'Next period expected', 'value' => 'Tue, Sep 29, 2026' ),
			array( 'label' => 'Cycle length used', 'value' => '28 days' ),
		),
	),
	'paint-calculator' => array(
		'label' => 'Paint to buy',
		'value' => '2 gallons',
		'note'  => 'Coverage is rounded up to whole cans because paint is not sold by the fraction. A bare, porous or sharply darker wall drinks more, so budget an extra coat on a colour change.',
		'rows'  => array(
			array( 'label' => 'Exact requirement', 'value' => '1.72 gal' ),
			array( 'label' => 'Paintable area', 'value' => '301 sq ft' ),
			array( 'label' => 'Wall area before openings', 'value' => '352 sq ft' ),
			array( 'label' => 'Openings deducted', 'value' => '51 sq ft' ),
			array( 'label' => 'Litres', 'value' => '6.5' ),
		),
	),
	'pay-raise-calculator' => array(
		'label' => 'New salary',
		'value' => '$62,400',
		'note'  => 'A raise only counts once inflation is taken out, which is why the real figure matters more than the headline one.',
		'rows'  => array(
			array( 'label' => 'Increase', 'value' => '$2,400' ),
			array( 'label' => 'Percentage raise', 'value' => '4%' ),
			array( 'label' => 'Extra per month', 'value' => '$200.00' ),
			array( 'label' => 'Extra per week', 'value' => '$46.15' ),
			array( 'label' => 'Real raise after 3% inflation', 'value' => '1%' ),
		),
	),
	'percent-change-calculator' => array(
		'label' => 'Percentage increase',
		'value' => '50%',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'From', 'value' => '50' ),
			array( 'label' => 'To', 'value' => '75' ),
			array( 'label' => 'Absolute change', 'value' => '25' ),
		),
	),
	'percent-off-calculator' => array(
		'label' => 'You pay',
		'value' => '$56.00',
		'note'  => 'Half off is the only discount most people can do reliably in their head. For everything else, take ten per cent and scale it.',
		'rows'  => array(
			array( 'label' => 'Original price', 'value' => '$80.00' ),
			array( 'label' => 'You save', 'value' => '$24.00' ),
			array( 'label' => 'Percent off', 'value' => '30%' ),
		),
	),
	'percentage-calculator' => array(
		'label' => '25% of 200',
		'value' => '50',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Percentage', 'value' => '25%' ),
			array( 'label' => 'Of', 'value' => '200' ),
			array( 'label' => 'Remainder', 'value' => '150' ),
		),
	),
	'percentage-decrease-calculator' => array(
		'label' => 'Decreased value',
		'value' => '170',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Original value', 'value' => '200' ),
			array( 'label' => 'Decrease of 15%', 'value' => '30' ),
			array( 'label' => 'As a multiplier', 'value' => '× 0.85' ),
		),
	),
	'percentage-increase-calculator' => array(
		'label' => 'Increased value',
		'value' => '230',
		'note'  => 'Adding a percentage and then removing the same percentage does not return you to the start, because the second calculation runs against the larger number.',
		'rows'  => array(
			array( 'label' => 'Original value', 'value' => '200' ),
			array( 'label' => 'Increase of 15%', 'value' => '30' ),
			array( 'label' => 'As a multiplier', 'value' => '× 1.15' ),
		),
	),
	'period-calculator' => array(
		'label' => 'Next period expected',
		'value' => 'Tue, Sep 29, 2026',
		'note'  => 'Straight cycle arithmetic. Real cycles vary by several days month to month, and stress, illness, travel and training all move them, so the later predictions are looser than the first.',
		'rows'  => array(
			array( 'label' => 'Period 1', 'value' => 'Tue, Sep 29, 2026 to Sat, Oct 3, 2026' ),
			array( 'label' => 'Period 2', 'value' => 'Tue, Oct 27, 2026 to Sat, Oct 31, 2026' ),
			array( 'label' => 'Period 3', 'value' => 'Tue, Nov 24, 2026 to Sat, Nov 28, 2026' ),
			array( 'label' => 'Period 4', 'value' => 'Tue, Dec 22, 2026 to Sat, Dec 26, 2026' ),
			array( 'label' => 'Period 5', 'value' => 'Tue, Jan 19, 2027 to Sat, Jan 23, 2027' ),
		),
	),
	'personal-loan-calculator' => array(
		'label' => 'Monthly payment',
		'value' => '$336.49',
		'note'  => 'Personal loans are unsecured, so the rate is driven almost entirely by your credit score. Origination fees are often deducted from the amount you receive rather than added to the balance, so check which way your lender does it.',
		'rows'  => array(
			array( 'label' => 'Amount financed', 'value' => '$15,300' ),
			array( 'label' => 'Total interest', 'value' => '$4,889' ),
			array( 'label' => 'Total of payments', 'value' => '$20,189' ),
			array( 'label' => 'Number of payments', 'value' => '60' ),
			array( 'label' => 'Cost per dollar borrowed', 'value' => '$1.32' ),
		),
	),
	'pool-volume-calculator' => array(
		'label' => 'Pool volume',
		'value' => '21,065 gallons',
		'note'  => 'Averaging the shallow and deep ends is accurate for a pool with a steady slope. A pool with a sharp drop-off or a spa step holds less than this suggests.',
		'rows'  => array(
			array( 'label' => 'Litres', 'value' => '79,740' ),
			array( 'label' => 'Cubic feet', 'value' => '2,816' ),
			array( 'label' => 'Average depth', 'value' => '5.5 ft' ),
		),
	),
	'pregnancy-calculator' => array(
		'label' => 'Estimated due date',
		'value' => 'Wed, Jan 6, 2027',
		'note'  => 'Only about one birth in twenty happens on the due date itself. A dating scan in the first trimester is considerably more accurate than any calculation from a period date.',
		'rows'  => array(
			array( 'label' => 'How far along today', 'value' => '24 weeks 2 days' ),
			array( 'label' => 'Trimester', 'value' => 'Second' ),
			array( 'label' => 'Days remaining', 'value' => '110' ),
			array( 'label' => 'Conception, approximately', 'value' => 'Wed, Apr 15, 2026' ),
			array( 'label' => 'Full term from', 'value' => 'Wed, Dec 16, 2026' ),
		),
	),
	'proportion-calculator' => array(
		'label' => 'Solving for d',
		'value' => '12',
		'note'  => 'A proportion holds when the two cross products match, which is the quickest way to check any answer here by hand.',
		'rows'  => array(
			array( 'label' => 'Method', 'value' => '(b × c) ÷ a' ),
			array( 'label' => 'Cross product', 'value' => '24 and 24' ),
		),
	),
	'pythagorean-theorem-calculator' => array(
		'label' => 'Side c',
		'value' => '5',
		'note'  => 'Works only for right triangles. For any other triangle, the law of cosines is the tool.',
		'rows'  => array(
			array( 'label' => 'From', 'value' => 'legs 3 and 4' ),
			array( 'label' => 'Area of the triangle', 'value' => '6' ),
			array( 'label' => 'Perimeter', 'value' => '12' ),
			array( 'label' => 'Angle opposite a', 'value' => '36.87°' ),
		),
	),
	'quadratic-formula-calculator' => array(
		'label' => 'Two real roots',
		'value' => 'x = 2 or 1',
		'note'  => 'A positive discriminant means the parabola crosses the x axis twice.',
		'rows'  => array(
			array( 'label' => 'Discriminant', 'value' => '1' ),
			array( 'label' => 'Vertex', 'value' => '(1.5, -0.25)' ),
			array( 'label' => 'Axis of symmetry', 'value' => 'x = 1.5' ),
		),
	),
	'ratio-calculator' => array(
		'label' => 'Missing value',
		'value' => '12',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Your ratio', 'value' => '3 : 4' ),
			array( 'label' => 'Simplified', 'value' => '3 : 4' ),
			array( 'label' => 'As a decimal', 'value' => '0.75' ),
			array( 'label' => 'Complete proportion', 'value' => '3 : 4 = 9 : 12' ),
		),
	),
	'right-triangle-calculator' => array(
		'label' => 'Hypotenuse',
		'value' => '5',
		'note'  => 'The three angles always total 180 degrees, and one of them is fixed at 90, so knowing one of the other two gives you the third for free.',
		'rows'  => array(
			array( 'label' => 'Angle A', 'value' => '36.87°' ),
			array( 'label' => 'Angle B', 'value' => '53.13°' ),
			array( 'label' => 'Angle C', 'value' => '90°' ),
			array( 'label' => 'Area', 'value' => '6' ),
			array( 'label' => 'Perimeter', 'value' => '12' ),
			array( 'label' => 'Inradius', 'value' => '1' ),
		),
	),
	'roman-numeral-converter' => array(
		'label' => '1994 in Roman numerals',
		'value' => 'MCMXCIV',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Characters', 'value' => '7' ),
			array( 'label' => 'Broken down', 'value' => 'M C M X C I V' ),
		),
	),
	'roth-ira-calculator' => array(
		'label' => 'Tax-free balance at retirement',
		'value' => '$760,491',
		'note'  => 'Roth contributions are made from money already taxed, so nothing is deducted now and nothing is owed on the growth later. That trade favours you when your tax rate in retirement is higher than it is today, which is usually the case early in a career.',
		'rows'  => array(
			array( 'label' => 'You contributed', 'value' => '$220,000' ),
			array( 'label' => 'Tax-free growth', 'value' => '$540,491' ),
			array( 'label' => 'Tax avoided on the growth', 'value' => '$118,908' ),
			array( 'label' => 'Annual contribution', 'value' => '$7,000' ),
		),
	),
	'sales-tax-calculator' => array(
		'label' => 'Total with tax',
		'value' => '$108.25',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Before tax', 'value' => '$100.00' ),
			array( 'label' => 'Sales tax', 'value' => '$8.25' ),
			array( 'label' => 'After tax', 'value' => '$108.25' ),
		),
	),
	'slope-calculator' => array(
		'label' => 'Slope',
		'value' => '2',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Equation', 'value' => 'y = 2x + 0' ),
			array( 'label' => 'Rise over run', 'value' => '8 / 4' ),
			array( 'label' => 'Angle', 'value' => '63.435°' ),
			array( 'label' => 'Distance between points', 'value' => '8.944272' ),
		),
	),
	'square-footage-calculator' => array(
		'label' => 'Total area',
		'value' => '120 sq ft',
		'note'  => 'Measure at the widest points and treat alcoves as separate rectangles, because rounding a room to one rectangle is the usual reason an order comes up short.',
		'rows'  => array(
			array( 'label' => 'Square metres', 'value' => '11.15 m2' ),
			array( 'label' => 'Square yards', 'value' => '13.33 sq yd' ),
			array( 'label' => 'Acres', 'value' => '0.0028 ac' ),
		),
	),
	'square-root-calculator' => array(
		'label' => 'Square root of 72',
		'value' => '8.48528137',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Simplified radical', 'value' => '6√2' ),
			array( 'label' => 'Cube root', 'value' => '4.16016765' ),
			array( 'label' => 'Squared back', 'value' => '72' ),
			array( 'label' => 'Perfect square', 'value' => 'no' ),
		),
	),
	'stair-calculator' => array(
		'label' => 'Steps needed',
		'value' => '15 risers',
		'note'  => 'Within typical residential limits, though local code always wins over any rule of thumb. Two risers plus one tread should land between 24 and 25 inches.',
		'rows'  => array(
			array( 'label' => 'Riser height', 'value' => '7.2 in' ),
			array( 'label' => 'Tread depth', 'value' => '10 in' ),
			array( 'label' => 'Total run', 'value' => '140 in' ),
			array( 'label' => 'Stringer length', 'value' => '176.82 in' ),
			array( 'label' => 'Rule of 25 check', 'value' => '24.4 in' ),
		),
	),
	'standard-deviation-calculator' => array(
		'label' => 'Sample standard deviation',
		'value' => '2.13809',
		'note'  => 'Dividing by n minus one corrects for the fact that a sample underestimates the spread of the population it came from.',
		'rows'  => array(
			array( 'label' => 'Variance', 'value' => '4.571429' ),
			array( 'label' => 'Mean', 'value' => '5' ),
			array( 'label' => 'Count', 'value' => '8' ),
			array( 'label' => 'Sum of squared deviations', 'value' => '32' ),
			array( 'label' => 'Coefficient of variation', 'value' => '42.762%' ),
		),
	),
	'steps-to-miles-calculator' => array(
		'label' => 'Distance covered',
		'value' => '4.56 miles',
		'note'  => 'Stride is estimated from height rather than measured, so this is an approximation. Pace, terrain and footwear all change it. To get an accurate figure, walk a measured distance and divide by your step count.',
		'rows'  => array(
			array( 'label' => 'Kilometres', 'value' => '7.34' ),
			array( 'label' => 'Estimated stride', 'value' => '28.9 in' ),
			array( 'label' => 'Steps per mile', 'value' => '2,192' ),
			array( 'label' => 'Rough calories burned', 'value' => '456 kcal' ),
		),
	),
	'system-of-equations-calculator' => array(
		'label' => 'Solution',
		'value' => 'x = 2, y = 1',
		'note'  => 'Solved by Cramer’s rule. The determinant is non-zero, so the two lines cross at exactly one point.',
		'rows'  => array(
			array( 'label' => 'x', 'value' => '2' ),
			array( 'label' => 'y', 'value' => '1' ),
			array( 'label' => 'Determinant', 'value' => '-3' ),
		),
	),
	'take-home-pay-calculator' => array(
		'label' => 'Take-home per year',
		'value' => '$51,650.10',
		'note'  => 'Income tax rates are entered rather than looked up, because brackets change yearly and depend on filing status and credits. For a precise figure use the IRS withholding estimator; for planning, your last return’s effective rate is the number to put in.',
		'rows'  => array(
			array( 'label' => 'Annual take-home', 'value' => '$51,650' ),
			array( 'label' => 'Income tax', 'value' => '$10,896' ),
			array( 'label' => 'Social Security & Medicare', 'value' => '$5,554' ),
			array( 'label' => 'Pre-tax deductions', 'value' => '$6,900' ),
			array( 'label' => 'Gross annual', 'value' => '$75,000' ),
			array( 'label' => 'Effective total rate', 'value' => '31.13%' ),
		),
	),
	'tdee-calculator' => array(
		'label' => 'Daily energy needs',
		'value' => '2,759 kcal',
		'note'  => 'Predicted rather than measured, so track your weight for a fortnight and adjust the figure to what actually happens.',
		'rows'  => array(
			array( 'label' => 'Resting rate (BMR)', 'value' => '1,780 kcal' ),
			array( 'label' => 'Activity on top', 'value' => '979 kcal' ),
			array( 'label' => 'Lose about 0.5kg a week', 'value' => '2,259 kcal' ),
			array( 'label' => 'Gain about 0.5kg a week', 'value' => '3,259 kcal' ),
		),
	),
	'tile-calculator' => array(
		'label' => 'Tiles to buy',
		'value' => '132 tiles',
		'note'  => 'Ten per cent waste covers ordinary cuts. Go to fifteen for a diagonal or herringbone layout, and buy the whole job in one batch because dye lots shift between production runs.',
		'rows'  => array(
			array( 'label' => 'Area to cover', 'value' => '120 sq ft' ),
			array( 'label' => 'Each tile covers', 'value' => '1 sq ft' ),
			array( 'label' => 'Boxes to buy', 'value' => '14' ),
			array( 'label' => 'Spare tiles in the last box', 'value' => '8' ),
		),
	),
	'time-calculator' => array(
		'label' => 'Time plus 3h 30m',
		'value' => '12:30 PM',
		'note'  => '',
		'rows'  => array(
			array( 'label' => '24 hour clock', 'value' => '12:30' ),
			array( 'label' => 'Day change', 'value' => 'same day' ),
			array( 'label' => 'Started at', 'value' => '9:00 AM' ),
		),
	),
	'time-card-calculator' => array(
		'label' => 'Total for the week',
		'value' => '37h 30m',
		'note'  => 'Overtime is calculated at time and a half above forty hours in a week, which is the federal FLSA rule. Some states, California among them, also pay overtime above eight hours in a single day.',
		'rows'  => array(
			array( 'label' => 'Day 1', 'value' => '7h 30m' ),
			array( 'label' => 'Day 2', 'value' => '7h 30m' ),
			array( 'label' => 'Day 3', 'value' => '7h 30m' ),
			array( 'label' => 'Day 4', 'value' => '7h 30m' ),
			array( 'label' => 'Decimal hours', 'value' => '37.5' ),
			array( 'label' => 'Regular hours', 'value' => '37.5' ),
			array( 'label' => 'Overtime hours', 'value' => '0' ),
			array( 'label' => 'Gross pay', 'value' => '$750.00' ),
		),
	),
	'time-duration-calculator' => array(
		'label' => 'Duration',
		'value' => '8h 30m',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Decimal hours', 'value' => '8.5' ),
			array( 'label' => 'Total minutes', 'value' => '510' ),
			array( 'label' => 'Crosses midnight', 'value' => 'yes' ),
			array( 'label' => 'From', 'value' => '10:00 PM to 6:30 AM' ),
		),
	),
	'tip-calculator' => array(
		'label' => 'Total to pay',
		'value' => '$100.30',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Bill', 'value' => '$85.00' ),
			array( 'label' => 'Tip at 18%', 'value' => '$15.30' ),
			array( 'label' => 'Each person pays', 'value' => '$50.15' ),
			array( 'label' => 'Tip per person', 'value' => '$7.65' ),
		),
	),
	'tire-size-calculator' => array(
		'label' => 'Overall diameter',
		'value' => '24.972 in',
		'note'  => 'Stay within about three per cent of the original diameter. Beyond that the speedometer, odometer and in many cars the traction control all read wrong, and the tyre may foul the arch on full lock.',
		'rows'  => array(
			array( 'label' => 'Sidewall height', 'value' => '101.3 mm' ),
			array( 'label' => 'Circumference', 'value' => '78.45 in' ),
			array( 'label' => 'Revolutions per mile', 'value' => '808' ),
			array( 'label' => 'Comparison diameter', 'value' => '25.402 in' ),
			array( 'label' => 'Difference', 'value' => '1.72%' ),
			array( 'label' => 'Speedo reads 60, actual', 'value' => '61 mph' ),
		),
	),
	'topsoil-calculator' => array(
		'label' => 'Topsoil to order',
		'value' => '4.26 cubic yards',
		'note'  => 'Weight is an average and varies with moisture and grade, so confirm the supplier’s own figure before ordering by the ton rather than by volume.',
		'rows'  => array(
			array( 'label' => 'Volume', 'value' => '115 cu ft' ),
			array( 'label' => 'Metric', 'value' => '3.26 m3' ),
			array( 'label' => 'Approx. weight', 'value' => '4.69 US tons' ),
		),
	),
	'triangle-calculator' => array(
		'label' => 'Right triangle area',
		'value' => '6',
		'note'  => 'Area is found with Heron’s formula, which needs only the three sides and no angle at all.',
		'rows'  => array(
			array( 'label' => 'Angle A', 'value' => '36.87°' ),
			array( 'label' => 'Angle B', 'value' => '53.13°' ),
			array( 'label' => 'Angle C', 'value' => '90°' ),
			array( 'label' => 'Perimeter', 'value' => '12' ),
			array( 'label' => 'Semi-perimeter', 'value' => '6' ),
			array( 'label' => 'Height on side a', 'value' => '4' ),
		),
	),
	'unit-converter' => array(
		'label' => '1 m converted',
		'value' => '3.28084 ft',
		'note'  => 'An inch has been defined as exactly 25.4 millimetres since 1959, so every conversion between the two systems is exact rather than approximate.',
		'rows'  => array(
			array( 'label' => 'Millimetres', 'value' => '1,000' ),
			array( 'label' => 'Centimetres', 'value' => '100' ),
			array( 'label' => 'Metres', 'value' => '1' ),
			array( 'label' => 'Inches', 'value' => '39.3701' ),
			array( 'label' => 'Feet', 'value' => '3.28084' ),
			array( 'label' => 'Miles', 'value' => '0.0006214' ),
		),
	),
	'vat-calculator' => array(
		'label' => 'Total including VAT',
		'value' => '$120.00',
		'note'  => 'Removing VAT means dividing by one plus the rate, not subtracting the percentage. Subtracting gives a number that is always too low, and the gap grows with the size of the bill.',
		'rows'  => array(
			array( 'label' => 'Excluding VAT', 'value' => '$100.00' ),
			array( 'label' => 'VAT amount', 'value' => '$20.00' ),
			array( 'label' => 'Including VAT', 'value' => '$120.00' ),
			array( 'label' => 'Rate applied', 'value' => '20%' ),
		),
	),
	'voltage-drop-calculator' => array(
		'label' => 'Voltage drop',
		'value' => '7.9 V',
		'note'  => 'Over the three per cent the NEC recommends for a branch circuit. Go up a wire size, shorten the run, or raise the supply voltage.',
		'rows'  => array(
			array( 'label' => 'Percentage drop', 'value' => '6.58%' ),
			array( 'label' => 'Voltage at the load', 'value' => '112.1 V' ),
			array( 'label' => 'Conductor', 'value' => 'AWG 12, copper' ),
			array( 'label' => '3% branch circuit limit', 'value' => 'Exceeded' ),
		),
	),
	'volume-calculator' => array(
		'label' => 'Box volume',
		'value' => '60 cubic units',
		'note'  => 'A cone and a pyramid are each exactly one third of the box or cylinder that would enclose them, which is worth remembering as a sanity check.',
		'rows'  => array(
			array( 'label' => 'If units are feet', 'value' => '60 cu ft' ),
			array( 'label' => 'That in cubic yards', 'value' => '2.2222' ),
			array( 'label' => 'If units are inches, in cubic feet', 'value' => '0.03472' ),
			array( 'label' => 'If feet, in US gallons', 'value' => '448.83' ),
		),
	),
	'water-intake-calculator' => array(
		'label' => 'Daily water target',
		'value' => '2.98 litres',
		'note'  => 'Food supplies roughly a fifth of daily fluid, and so do tea, coffee and other drinks, so this is total intake rather than plain water you must drink. Thirst and pale urine are better day to day guides than any number.',
		'rows'  => array(
			array( 'label' => 'US fluid ounces', 'value' => '101' ),
			array( 'label' => 'Cups (8 oz)', 'value' => '12.6' ),
			array( 'label' => 'Baseline for your weight', 'value' => '2.63 L' ),
			array( 'label' => 'Added for exercise', 'value' => '0.35 L' ),
		),
	),
	'weight-converter' => array(
		'label' => '70 kg converted',
		'value' => '154.3237 lb',
		'note'  => 'A US ton is 2,000 pounds and a metric tonne is 1,000 kilograms, which is about 2,205 pounds. They differ by roughly ten per cent, so the spelling matters on an invoice.',
		'rows'  => array(
			array( 'label' => 'Kilograms', 'value' => '70' ),
			array( 'label' => 'Pounds', 'value' => '154.3237' ),
			array( 'label' => 'Ounces', 'value' => '2,469.179' ),
			array( 'label' => 'Grams', 'value' => '70,000' ),
			array( 'label' => 'Stone', 'value' => '11.0231' ),
			array( 'label' => 'US tons', 'value' => '0.07716' ),
		),
	),
	'work-hours-calculator' => array(
		'label' => 'Weekly hours',
		'value' => '35h 0m',
		'note'  => '',
		'rows'  => array(
			array( 'label' => 'Per day', 'value' => '7h 0m' ),
			array( 'label' => 'Decimal weekly hours', 'value' => '35' ),
			array( 'label' => 'Over 40 hours', 'value' => 'none' ),
			array( 'label' => 'Weekly pay at $25.00', 'value' => '$875.00' ),
			array( 'label' => 'Annual, 52 weeks', 'value' => '$45,500.00' ),
		),
	),
);
